name: "speech_to_text"

data:
    language: "indonesian" # Common Voice language
    train: "train.tsv"
    dev: "dev.tsv"
    test: "test.tsv"
    level: "word"
    lowercase: False
    max_sent_length: 25
    src_voc_min_freq: 0
    src_voc_limit: 100
    trg_voc_min_freq: 0
    trg_voc_limit: 100

testing:
    beam_size: 1
    alpha: 1.0

training:
    optimizer: "adam"
    learning_rate: 0.0002
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 20
    batch_type: "sentence"
    scheduling: "plateau"
    patience: 5
    decrease_factor: 0.5
    early_stopping_metric: "loss"
    epochs: 2
    validation_freq: 100
    logging_freq: 50
    eval_metric: "bleu"
    model_dir: "stt_model"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 30
    print_valid_sents: [0, 3, 6]
    keep_last_ckpts: 2

model:
    initializer: "xavier"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    bias_initializer: "zeros"
    init_rnn_orthogonal: False
    lstm_forget_gate: 0.
    encoder:
        rnn_type: "gru"
        embeddings:
            embedding_dim: 40
            scale: False
        hidden_size: 5
        bidirectional: True
        dropout: 0.1
        num_layers: 7
    decoder:
        rnn_type: "gru"
        embeddings:
            embedding_dim: 16
            scale: False
        hidden_size: 5
        dropout: 0.1
        hidden_dropout: 0.1
        num_layers: 7
        input_feeding: True
        init_hidden: "zero"
        attention: "bahdanau"
