name: "speech_to_text"

data:
    language: "interlingua" # Common Voice language
    train: "train.tsv"
    dev: "dev.tsv"
    test: "test.tsv"
    level: "char"
    lowercase: True
    max_sent_length: 25
    src_voc_min_freq: 0
    src_voc_limit: 100
    trg_voc_min_freq: 0
    trg_voc_limit: 100

testing:
    beam_size: 1
    alpha: 1.0

training:
    optimizer: "adam"
    learning_rate: 0.0002
    learning_rate_min: 0.0000005
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 20
    batch_type: "sentence"
    scheduling: "plateau"
    patience: 4
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 10
    validation_freq: 200
    logging_freq: 50
    eval_metric: "bleu"
    model_dir: "stt_model"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2]
    keep_last_ckpts: 2

model:
    encoder:
        rnn_type: "lstm" # gru
        embeddings:
            embedding_dim: 128 # 512
            scale: False
        hidden_size: 5
        bidirectional: True
        dropout: 0.2
        num_layers: 7
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 512
            scale: False
        emb_scale: False
        hidden_size: 1024
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 4
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"
